version: '3.7'
services:
  postgres:
    image: postgres:15.2
    restart: always
    environment:
      - POSTGRES_USER=AppUser
      - POSTGRES_PASSWORD=s51rW9sAdFf5Ww2!uem
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: