endpoint-roles:
  mappings:

    #FIXME this is for test reason, clear it
    - endpoint: "/api/payment/v1/test"
      method: "GET"
      roles: [ "ROLE_ADMIN" ]
    - endpoint: "/api/payment/v1/mest"
      method: "GET"
      roles: [ "ROLE_ADMIN" ]
    - endpoint: "/api/payment/v1/dost"
      method: "POST"
      roles: [ "ROLE_ADMIN" ]
    - endpoint: "/api/payment/v1/dost"
      method: "GET"
      roles: [ ]

#                                       USER_ROLE_MAPPINGS
    #    statistics
    - endpoint: "/api/users/v1/statistics/public"
      method: "GET"
      roles: [ ]

    #    users
    - endpoint: "/api/users/v1/user/info"
      method: "GET"
      roles: [ "ROLE_USER" ]

    #    cards
    - endpoint: "/api/cards/v1/info"
      method: "GET"
      roles: [ "ROLE_USER" ]
    - endpoint: "/api/cards/v1/top-up"
      method: "PUT"
      roles: [ "ROLE_USER" ]