endpoint-roles:
  mappings:
    #    statistics
    - endpoint: "/api/users/v1/statistics/public"
      method: "GET"
      roles: [ ]

    #    users
    - endpoint: "/api/users/v1/user/info"
      method: "GET"
      roles: [ "ROLE_USER" ]

    #    cards
    - endpoint: "/api/cards/v1/info"
      method: "GET"
      roles: [ "ROLE_USER" ]
    - endpoint: "/api/cards/v1/top-up"
      method: "PUT"
      roles: [ "ROLE_USER" ]

    #    transfer
    - endpoint: "/api/transfer/v1/card-to-card"
      method: "POST"
      roles: [ "ROLE_USER" ]


    #    logs
    - endpoint: "/api/logs/v1/logs/user"
      method: "GET"
      roles: [ "ROLE_USER" ]