package com.example.transferms.api.model;

import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import java.math.BigDecimal;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class TransferRequestDto {

    @NotBlank
    String fromCard;

    @NotBlank
    String toCard;

    @Min(1)
    @NotNull
    private BigDecimal amount;

    @Min(999)
    @NotNull
    private Long transactionNumber;//generated by client
}
