spring:
  port: 8080
  application:
    name: gw

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81}

  main:
    web-application-type: REACTIVE
  profiles:
    include:
      - env

logging:
  level:
    org.springframework.cloud.gateway.filter.rate-limit: DEBUG

jwt:
  secret:
    key: ${JWT_SECRET_KEY:89937fa2775fa5246308c6c3d1e7fe1e233c6cf2d1e381e96e54b4a079cc80d26268ca985f63dcbe2b68b13828dc921d63baf4d1d8a4f4021c786b647daab15a}