auth-ms:
  url: ${AUTH-MS_URL:http://localhost:8081}
user-ms:
  url: ${USER-MS_URL:http://localhost:8082}
card-ms:
  url: ${CARD-MS_URL:http://localhost:8083}
transfer-ms:
  url: ${TRANSFER-MS_URL:http://localhost:8084}
log-ms:
  url: ${LOG-MS_URL:http://localhost:8085}
