spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:cardms}
    username: ${DB_USER:AppUser}
    password: ${DB_PASSWORD:s51rW9sAdFf5Ww2!uem}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        default_schema: "cardms"
        default_batch_fetch_size: 10
    open-in-view: false
